name: GHL Demo to Abacus AI Chat Integration

on:
  repository_dispatch:
    types: [ghl-chat-message]
  workflow_dispatch:

jobs:
  process-chat:
    runs-on: ubuntu-latest
    
    steps:
    - name: Process GHL Chat Message
      run: |
        echo "Processing chat message from GHL Demo"
        echo "Message: ${{ github.event.client_payload.message }}"
        echo "Contact ID: ${{ github.event.client_payload.contact_id }}"
        echo "Conversation ID: ${{ github.event.client_payload.conversation_id }}"
    
    - name: Send to Abacus ChatLLM
      id: abacus
      run: |
        response=$(curl -s -X POST "https://api.abacus.ai/api/v0/chatLLM" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.ABACUS_API_KEY }}" \
          -d "{\"messages\": [{\"role\": \"user\", \"content\": \"${{ github.event.client_payload.message }}\"}]}")
        
        echo "Raw Abacus Response: $response"
        
        message_content=$(echo "$response" | jq -r '.response // .content // .message // .text // .choices[0].message.content // "Error: No response found"')
        echo "abacus_response=$message_content" >> $GITHUB_OUTPUT
        echo "Extracted Response: $message_content"
    
    - name: Send Response Back to GHL Demo
      run: |
        curl -X POST "https://services.leadconnectorhq.com/conversations/${{ github.event.client_payload.conversation_id }}/messages" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.GHL_API_KEY_DEMO }}" \
          -H "Version: 2021-07-28" \
          -d "{\"type\": \"SMS\", \"message\": \"${{ steps.abacus.outputs.abacus_response }}\", \"contactId\": \"${{ github.event.client_payload.contact_id }}\"}"
        
        echo "Response sent back to GHL Demo"
